fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "justlikephp@gmail.com" # Wouldn't normally hard code these.
        sender_name: "Nathan Daly"